ls:
  .js: kebab-case
  .jsx: kebab-case
  .ts: kebab-case
  .tsx: kebab-case
  .config.js: kebab-case
  .d.ts: kebab-case
  .json: kebab-case
  .md: kebab-case
ignore:
  - node_modules
  - ./.next
  - ./pages
  - ./node_modules
