name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI
        run: |
          npm ci # Clean install dependencies.
          npm run typecheck # Run TypeScript compiler.
          npm run format # Run formatter.
          npm run lint # Run linter.
          npm run build # Run build.
